export const users = [
  {
    id: 1,
    name: 'Creight',
    birthday: '7/11/2003',
    age: 19,
    email: 'cbulloch0@wix.com',
    country: 'Russia',
    company: 'Flashspan',
  },
  {
    id: 2,
    name: 'Abigail',
    birthday: '9/6/1992',
    age: 30,
    email: 'aklemz1@ocn.ne.jp',
    country: 'China',
    company: 'Bluezoom',
  },
  {
    id: 3,
    name: 'Dael',
    birthday: '9/9/2003',
    age: 19,
    email: 'dlynskey2@jugem.jp',
    country: 'China',
    company: 'Buzzster',
  },
  {
    id: 4,
    name: 'Nancey',
    birthday: '6/25/1991',
    age: 31,
    email: 'nmargarson3@plala.or.jp',
    country: 'Bulgaria',
    company: 'Demivee',
  },
  {
    id: 5,
    name: 'Waverly',
    birthday: '3/29/2001',
    age: 21,
    email: 'wparnham4@edublogs.org',
    country: 'Indonesia',
    company: 'Jabberstorm',
  },
  {
    id: 6,
    name: 'Maynard',
    birthday: '5/21/1993',
    age: 29,
    email: 'mfurminger5@google.co.uk',
    country: 'Bulgaria',
    company: 'Fivespan',
  },
  {
    id: 7,
    name: 'Rosaline',
    birthday: '5/21/1991',
    age: 31,
    email: 'rmillom6@java.com',
    country: 'Indonesia',
    company: 'Oloo',
  },
  {
    id: 8,
    name: 'Slade',
    birthday: '4/25/1994',
    age: 28,
    email: 'sturland7@posterous.com',
    country: 'Azerbaijan',
    company: 'Gabspot',
  },
  {
    id: 9,
    name: 'Lemuel',
    birthday: '6/8/1996',
    age: 26,
    email: 'lgunton8@skyrock.com',
    country: 'Philippines',
    company: 'Voolith',
  },
  {
    id: 10,
    name: 'Ricky',
    birthday: '8/16/1991',
    age: 31,
    email: 'rmagill9@techcrunch.com',
    country: 'Portugal',
    company: 'Innojam',
  },
];
